version: '3.7'
name: 'reactss'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'data:/app'
      - 'node_modules:/app/node_modules'
    ports:
      - 3001:3000

volumes:
  data:
  node_modules: